version: '3.7'
services:
  legocollector:
    container_name: legocollector
    image: futtie/legocollector:local
    ports:
      - 8080:8080
    volumes:
      - /home/mhe/docker/legocollector/files/:/files/
    networks:
        - bridge 
  dbserver:
    container_name: dbserver
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Password1! 
      - MYSQL_USER=legouser 
      - MYSQL_PASSWORD=legopassword 
      - MYSQL_DATABASE=legoparts
    volumes:
      - /home/mhe/docker/mysql/data/:/var/lib/mysql/
    networks:
        - bridge
networks:
    bridge:
        external: true      
